language: java
jdk:
  - openjdk14

sudo: false

install: true

script: mvn clean package -DskipTests=true

notifications:
  email:
    recipients: "-maksimus.s@mail.ru"
    on_success: never
    on_failure: always
