language: java
jdk:
  - openjdk14

sudo: false

install: true

script: mvn clean package -DskipTests=true

notifications:
  email:
    recipients: "-maksimus.s@mail.ru"
    on_success: never
    on_failure: always

deploy:
  provider: heroku
  api_key: 4e478422-4130-49c0-bb91-41656920e0f5
  app: afternoon-beyond-85611
